### ISSUE TITLE
Revisão dos capitulos

### ISSUE THREAD

**Issue by valenca13** [U-Shift/Transport-Demand-Modelling#14]
Assinalar com **x** os que já foram revistos
- [x] 1. Exploratory Data Analysis
- [x] 2. Multiple Linear Regression models
- [x] 3. Exploratory Factor Analysis
- [x] 4. Cluster Analysis
- [x] 5. Generalized linear models
- [x] 6. Spatial regression models
- [x] 7. Panel Data Models
- [x] 8. Discrete Choice Models
- [x] - Multinomial
- [x] - Nested
- [x] - Ordered Models
- [x] 9. Hazard-Based Duration Models

**Comment by temospena** [comment]
@mncosta as imagens do não estão em lado nenhum... estão quebradas. parece-me que não foi de nenhuma alteração recente

**Comment by mncosta** [comment]
> 
> 
> @mncosta as imagens do não estão em lado nenhum... estão quebradas. parece-me que não foi de nenhuma alteração recente

Done.
