### ISSUE TITLE
Organização do repositório

### ISSUE THREAD

**Issue by temospena** [U-Shift/Transport-Demand-Modelling#15]
Este repositório está um bocado confuso.
Sugestão: depois de pensar numa estrutura de pastas, e do que mostrar ou esconder na listagem da pagina inicial, usar o [ezknitr](https://cran.r-project.org/web/packages/ezknitr/README.html) para ter os .md e os Rmd em locais separados.

_Originally posted by @temospena in https://github.com/U-Shift/Transport-Demand-Modelling/issues/4#issuecomment-729034815_

**Comment by temospena** [comment]
Dei uma volta na organização, mas não encontrei uma maneira perfeita de fazer o render de cada página `.Rmd`.
Por enquanto é apenas seguir o que está em [RmdFiles/knit.R](https://github.com/U-Shift/Transport-Demand-Modelling/blob/master/RmdFiles/knit.R).

- Agora no root só aparecem os .md e as pastas
- RmdFiles > com todos os .Rmd e as imagens que os suportam
- Data
- Code
- os slides e HA continuam a estar em releases, com link nos Slides.md.

Resolvi também a questão das tabelas desformatadas no `summarytools`, mas não podemos é apagar a pasta "tmp" :)

Não corrigi nem alterei nada de palavras, foi só estrutura.

Fica a faltar:
- criar imagem para media card, para quando se divulgar o repositório aparecer uma imagem (@valenca13 )
- corrigir as imagens que faltam em [0-Install_PythonBiogeme_win.md](https://github.com/U-Shift/Transport-Demand-Modelling/blob/master/0-Install_PythonBiogeme_win.md) #14  (@mncosta)
- quando estiver tudo sem espinhas, fazer uma nova release 2020.2 e actualizar o doi no zenodo #16 (@temospena )

Não olhei para a questão do "pages", porque não percebi como criar em dois cliques, e acho que não é prioridade. Mas se alguém quiser explorar, força!

Está quase 🪁

**Comment by mncosta** [comment]
Eu posso tratar do pages quando tiver um bocadinho.

**Comment by valenca13** [comment]
Olho pra imagem hoje a noite @temospena . Vou também fazer umas edições no texto. Utilizo o RMD do R e faço commit?

**Comment by temospena** [comment]
@valenca13 

> Utilizo o RMD do R e faço commit?
Sim. 
Fazes as alterações, carregas em knit, verificas se no preview está tudo bem. 
Se sim, **lê as instruções do último chunk** e corre-o, para os ficheiros irem para as pastas certas.

Antes de tudo, precisas de instalar uma única vez isto:  `install.packages("rprojroot")`

**Comment by valenca13** [comment]
@temospena @mncosta @filmoura já coloquei a imagem no MEDIACARD. Preferi deixar a imagem sem o simbolo do U-shift devido ao tamanho. Também fiz toda a revisão dos capítulos, ajustando alguns pequenos erros de digitação. 
Não sei se precisa de mais alguma coisa, se o @filmoura quer ainda olhar. Por mim está pronto para atualizar o DOI e compartilhar.

**Comment by temospena** [comment]
acho que falta só confirmar se o HA3 pode ficar disponível.
depois disso posso atualizar e fechar ambos os issues.

**Comment by temospena** [comment]
H3 com link na página oficial da cadeira.
nova release. vou encerrar.
